### ISSUE TITLE
Finalizar primeira entrega

### ISSUE THREAD

**Issue by omadson** [rodolforicardotech/datadiscoveryone#1]
Como combinado, a primeira entrega consistia em uma análise exploratória dos dados que escolheram. Para tal, vocês necessitam estar com o respositório organizado e ainda faltam algumas coisas. Ontem resolvemos alguns problemas, mas ainda faltam algumas coisas, a saber:

 - [x] Criar repositório
 - [x] Preencher README com as informações do projeto
 - [x] Atualizar o respositório com a análise exploratória
 - [x] Criar release no github com o título `Entrega 1` e a tag `v0.1.0`
 
A medida que forem concluindo estas tarefas, podem ir preenchendo os checkboxes. Qualquer dúvida, podem falar nessa issue.

**Comment by natorjunior** [comment]
**Análise Exploratória de dados** 

- [x] Quantificando os reviews;
- [x] Criação de categorias, positivo e negativo;
- [x] Transformação dos textos em caracteres minúsculo;
- [x] Remoção de caracteres especiais;
- [x] Remoção de nomes das casas de Game of Thrones;
- [x] Remoção de acentuação no texto;
- [x] Nuvem de palavras com as stop words;
- [x] Remover os stop words;
- [x] Representação dos dados com Bag of Words;
- [x] Separação de dados em treino e teste;
- [x] Criação do primeiro experimento de classificação, com Gaussian Naive Bayes;
